### ISSUE TITLE
Should be available via bower.

### ISSUE THREAD

**Issue by natecox** [kelvintaywl/dentist.js#2]
Cool library, but it'd be a lot easier on my workflow if you make it available via bower. I couldn't find anything on it there.

**Comment by kelvintaywl** [comment]
Hey there @natecox! 
thanks for the suggestion and compliments. I have now registered this as a Bower package!
You can now install it via Bower:

```
bower install dentistjs
```

**Comment by natecox** [comment]
Awesome, thanks for the response.
